### ISSUE TITLE
Description of action space and observation space

### ISSUE THREAD

**Issue by rebecajohn** [AGI-Labs/toto_benchmark#11]
What are the 7 things of obs and actions ?
Are the actions nothing but the torque applied on each joint?
And observation indicate the angular position of each joint ? 
A README on this is highly appreciated .

**Comment by gaoyuezhou** [comment]
Hi,

Thank you for your question. Please refer to our Readme [here](https://github.com/AGI-Labs/toto_benchmark/tree/main/assets) for information about all fields. Let us know if there are any additional questions, thanks!
