### ISSUE TITLE
Scooping data and embeddings

### ISSUE THREAD

**Issue by kaustubhsridhar** [AGI-Labs/toto_benchmark#2]
Hi, 

I'm having a little issue unzipping the scooping dataset as it is not recognized as a zip file. Do you perhaps notice a similar issue with the scooping zip file in the drive folder?

Also, I can't find the following pkl's inside the dataset zip files? Should I be looking elsewhere?
```
scooping_parsed_with_embeddings_moco_conv5_robocloud.pkl
pouring_parsed_with_embeddings_moco_conv5_robocloud.pkl
```

**Comment by gaoyuezhou** [comment]
Hi, 

Thank you for catching this. We have noticed the deprecated zip file issue for the scooping dataset, and we have uploaded the data to Google Cloud Bucket for better access. Please use [this link](https://console.cloud.google.com/storage/browser/toto-dataset) to download the scooping dataset instead.

Regarding your second question about the pickle files, we apologize for any confusion caused. The files have now been positioned inside the same Google Drive folder [here](https://drive.google.com/drive/folders/1JGPGjCqUP4nUOAxY3Fpx3PjUQ_loo7fc?usp=share_link). 

Hope this helps. Please let us know if there are any additional questions. Thank you!

**Comment by kaustubhsridhar** [comment]
Thank you very much. :)
