### ISSUE TITLE
Error in training 

### ISSUE THREAD

**Issue by Sun-r1s3** [AGI-Labs/toto_benchmark#9]
I have followed all the instruction for downloading the dataset and configuring the developement env, however when running the following command:
`python scripts/train.py --config-name train_bc.yaml data.pickle_fn=../assets/cloud-data-scooping/scooping_parsed_with_embeddings_moco_conv5.pkl `
I have the following error:
```
Traceback (most recent call last):
  File "scripts/train.py", line 101, in main
    agent.train(data)
  File "/home/ai-ray/projects/toto_benchmark/toto_benchmark/agents/BaseAgent.py", line 46, in train
    self.compute_loss(sample)
  File "/home/ai-ray/projects/toto_benchmark/toto_benchmark/agents/BCAgent.py", line 17, in compute_loss
    output = self.forward(sample)
  File "/home/ai-ray/projects/toto_benchmark/toto_benchmark/agents/BCAgent.py", line 14, in forward
    return self.models['decoder'](sample['inputs'])
  File "/home/ai-ray/mambaforge/envs/toto-benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ai-ray/projects/toto_benchmark/toto_benchmark/agents/BCAgent.py", line 97, in forward
    h = (observations - self.inp_mean) / self.inp_std
RuntimeError: The size of tensor a (7) must match the size of tensor b (2055) at non-singleton dimension 1
```
I noticed that the name of the pkl file with data parsed with moco is different (missing a _robocloud at the end of the name), could the format of the file have changed?

**Comment by gaoyuezhou** [comment]
Hi,

Sorry for the confusion. This is due to a mismatch in the training code and the dataset. We have pushed a fix to `scripts/train.py` which should solve the issue. Please let me know if there are additional questions.

For context, the `'observations'` key in the dataset contains only jointstates (dim 7) although `scripts/train.py` previously assumes the `'observations'` key contain the concatenation of jointstates (dim 7) with image embeddings (dim 2048). The fix is to concatenate `'observations'` with `'embeddings'` for each trajectory in the dataset.

**Comment by Sun-r1s3** [comment]
Thanks for the clarification, the training script is now working for the pouting dataset, while the scooping data the process is killed at some point (after loading the trajectory data) without any output... :-| 
<pre>(toto-benchmark) <font color="#26A269"><b>ai-ray@mimas</b></font>:<font color="#12488B"><b>~/projects/toto_benchmark/toto_benchmark</b></font>$ /home/ai-ray/mambaforge/envs/toto-benchmark/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn(&apos;resource_tracker: There appear to be %d &apos;
python scripts/train.py --config-name train_bc.yaml data.pickle_fn=../assets/scooping_parsed_with_embeddings_moco_conv5.pkl 
Model saved dir:  /home/ai-ray/projects/toto_benchmark/toto_benchmark/outputs/2023-08-06/15-16-17
default:
- override hydra/output: local
- override hydra/launcher: local
data:
  pickle_fn: ../assets/scooping_parsed_with_embeddings_moco_conv5.pkl
  subsample_period: 1
  in_dim: 2055
  out_dim: 7
  H: 50
  top_k: null
  images:
    cameras: []
    im_h: 480
    im_w: 640
    per_img_out: 2048
    crop: true
  noise: 0.0
  logs_folder: ../assets
agent:
  type: bcimage_pre
  vision_model: moco_conv5_robocloud
  vision_model_path: None
  description: NA
  hidden_dim: 128
training:
  lr: 0.001
  seed: 0
  epochs: 80
  device: cuda:0
  batch_size: 128
  save_every_x_epoch: 10
debug: true
saved_folder: /home/ai-ray/projects/toto_benchmark/toto_benchmark/outputs/2023-08-06/15-16-17

/home/ai-ray/projects/toto_benchmark/toto_benchmark ../assets/scooping_parsed_with_embeddings_moco_conv5.pkl
<font color="#12488B"><b>wandb</b></font>: Currently logged in as: <font color="#A2734C">diego-dallalba</font> (<font color="#A2734C">sano-science</font>). Use <b>`wandb login --relogin`</b> to force relogin
<font color="#12488B"><b>wandb</b></font>: wandb version 0.15.8 is available!  To upgrade, please run:
<font color="#12488B"><b>wandb</b></font>:  $ pip install wandb --upgrade
<font color="#12488B"><b>wandb</b></font>: Tracking run with wandb version 0.12.17
<font color="#12488B"><b>wandb</b></font>: Run data is saved locally in <font color="#A347BA"><b>/home/ai-ray/projects/toto_benchmark/toto_benchmark/outputs/2023-08-06/15-16-17/wandb/run-20230806_151618-1lw6is71</b></font>
<font color="#12488B"><b>wandb</b></font>: Run <b>`wandb offline`</b> to turn off syncing.
<font color="#12488B"><b>wandb</b></font>: Syncing run <font color="#A2734C">fearless-water-19</font>
<font color="#12488B"><b>wandb</b></font>: ⭐️ View project at <font color="#12488B"><u style="text-decoration-style:single">https://wandb.ai/sano-science/toto-bc</u></font>
<font color="#12488B"><b>wandb</b></font>: 🚀 View run at <font color="#12488B"><u style="text-decoration-style:single">https://wandb.ai/sano-science/toto-bc/runs/1lw6is71</u></font>
Using 1309 number of successful trajs. Total trajs: 1895
Killed
</pre>

**Comment by gaoyuezhou** [comment]
Hi,

The process being killed is mostly because the run time memory needed by the process is too large. Terminating other processes before launching this experiment may help.
